import type { RuntimeSnapshot } from '../../contracts'
import { fmtInt } from '../../shared/format'
import { evaluateRisk } from '../../shared/risk'
import { Dot } from './mm'

/**
 * The single place system health lives. Each item is a state in words, not a bare dot:
 * Feed (data source), Engine (strategy process), Risk (limit evaluation).
 */
export function StatusBar({ runtime, mid }: { runtime: RuntimeSnapshot; mid: number }) {
  const s = runtime.strategy
  const risk = evaluateRisk(s, runtime.riskLimits, runtime.initialCapital, mid, runtime.orderRatePerSec)
  const engine =
    s.status === 'RUNNING'
      ? { dot: 'ok' as const, text: 'running' }
      : s.halted
        ? { dot: 'bad' as const, text: 'halted' }
        : { dot: 'warn' as const, text: s.status.toLowerCase() }
  const riskDot = risk.level === 'breach' ? 'bad' : risk.level === 'warn' ? 'warn' : 'ok'
  return (
    <footer className="mm-status">
      <div className="grp">
        <span className="mm-sim" title="No exchange connection. Market data, fills and P&L are generated by a deterministic simulator.">
          Simulated data
        </span>
        <span><Dot state="ok" />Feed: synthetic · seq {fmtInt(runtime.orderBook.sequence)}</span>
        <span><Dot state={engine.dot} />Engine: {engine.text}</span>
        <span><Dot state={riskDot} />Risk: {risk.label.toLowerCase()}</span>
      </div>
      <div className="grp">
        <span className="faint">Ctrl+K  Commands</span>
      </div>
    </footer>
  )
}
