// P0.3 — fetch ONE real response per endpoint into fixtures/gt/ and report present/missing for every expected field (03 §3.1).
import { writeFileSync, mkdirSync } from 'node:fs';
import { GT_BASE, GT_ACCEPT, getJson } from './lib.mjs';

const H = { headers: { Accept: GT_ACCEPT } };
const get = (o, path) => path.split('.').reduce((a, k) => (a && typeof a === 'object' ? a[k] : undefined), o);
const POOL = ['address', 'name', 'pool_created_at', 'base_token_price_usd', 'fdv_usd', 'market_cap_usd', 'reserve_in_usd', 'volume_usd.m5', 'volume_usd.h1', 'volume_usd.h24',
  'price_change_percentage.m5', 'price_change_percentage.h1', 'transactions.m5.buys', 'transactions.m5.sells', 'transactions.m5.buyers', 'transactions.m5.sellers', 'transactions.h1.buys', 'transactions.h1.sells', 'transactions.h1.buyers', 'transactions.h1.sellers'];
const TRADE = ['tx_hash', 'tx_from_address', 'kind', 'block_timestamp', 'block_number', 'volume_in_usd', 'from_token_amount', 'to_token_amount', 'price_from_in_usd', 'price_to_in_usd'];
mkdirSync('fixtures/gt', { recursive: true });
const rows = [];
const check = (label, obj, names) => { for (const n of names) rows.push({ endpoint: label, field: n, status: get(obj, n) !== undefined ? 'present' : 'MISSING' }); };
const save = (name, r) => writeFileSync(`fixtures/gt/${name}.json`, JSON.stringify(r.json, null, 2));

const np = await getJson(`${GT_BASE}/networks/solana/new_pools?include=base_token,quote_token,dex&page=1`, H);
if (!np.ok) { console.error(`new_pools failed: ${np.status} ${np.error ?? ''}`); process.exit(1); }
save('new_pools', np);
const pools = np.json?.data ?? [];
check('new_pools', pools[0]?.attributes, POOL);
rows.push({ endpoint: 'new_pools', field: 'pools per page', status: String(pools.length) });
rows.push({ endpoint: 'new_pools', field: 'relationships.base_token.data.id', status: String(get(pools[0], 'relationships.base_token.data.id') ?? 'MISSING') });
let maxPage = 1;
for (const p of [2, 3, 5, 10]) { const r = await getJson(`${GT_BASE}/networks/solana/new_pools?page=${p}`, H); if (r.ok && (r.json?.data ?? []).length) maxPage = p; else break; }
rows.push({ endpoint: 'new_pools', field: 'max page served (probed 2,3,5,10)', status: String(maxPage) });

const addrs = pools.slice(0, 5).map((p) => p.attributes.address);
const multi = await getJson(`${GT_BASE}/networks/solana/pools/multi/${addrs.join(',')}?include=base_token,quote_token,dex`, H);
if (multi.ok) { save('pools_multi', multi); check('pools/multi', multi.json?.data?.[0]?.attributes, POOL); } else rows.push({ endpoint: 'pools/multi', field: '(request)', status: `FAILED ${multi.status}` });
const tr = await getJson(`${GT_BASE}/networks/solana/pools/${addrs[0]}/trades`, H);
if (tr.ok) { save('trades', tr); check('trades', tr.json?.data?.[0]?.attributes, TRADE); } else rows.push({ endpoint: 'trades', field: '(request)', status: `FAILED ${tr.status}` });
const oh = await getJson(`${GT_BASE}/networks/solana/pools/${addrs[0]}/ohlcv/minute?aggregate=1&limit=100`, H);
if (oh.ok) { save('ohlcv', oh); rows.push({ endpoint: 'ohlcv', field: 'data.attributes.ohlcv_list[0] = [t,o,h,l,c,v]', status: Array.isArray(get(oh.json, 'data.attributes.ohlcv_list.0')) ? 'present' : 'MISSING' }); } else rows.push({ endpoint: 'ohlcv', field: '(request)', status: `FAILED ${oh.status}` });
const mint = String(get(pools[0], 'relationships.base_token.data.id') ?? '').replace(/^solana_/, '');
const info = mint ? await getJson(`${GT_BASE}/networks/solana/tokens/${mint}/info`, H) : { ok: false, status: 0 };
if (info.ok) save('token_info', info); else rows.push({ endpoint: 'tokens/info', field: '(request)', status: `FAILED ${info.status}` });

console.table(rows);
const md = ['# FIELDS (generated by scripts/p0/fields.mjs)', '', '| Endpoint | Field | Status |', '|---|---|---|', ...rows.map((r) => `| ${r.endpoint} | ${r.field} | ${r.status} |`),
  '', 'Reference SOL/USDC pool address (owner chooses, P0.5): `TODO`'].join('\n');
writeFileSync('docs/build-spec/FIELDS.generated.md', md + '\n');
console.info('Wrote fixtures/gt/*.json and docs/build-spec/FIELDS.generated.md. Merge the table into FIELDS.md; real names that differ must be fixed in src/main/sources/normalize.ts.');
