[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "ticklab"
version = "0.1.0"
dependencies = []

[tool.black]
line-length = 88
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 88

[tool.flake8]
max-line-length = 88
exclude = ".git,__pycache__,build,dist,*.egg-info"

[tool.pytest]
testpaths = ["tests"]